// ============================================================================
// Pebble — Context Tree
// Writes memories as human-readable markdown files in a folder structure.
// These files can be git-tracked, shared with teams, and read by any AI tool
// even without MCP.
// ============================================================================

import type Database from "better-sqlite3";
import fs from "fs";
import path from "path";
import { getActiveMemories } from "./db.js";
import { type Memory, type MemoryCategory, type PebbleConfig, DEFAULT_CONFIG, PEBBLE_DIR } from "./types.js";

const CONTEXT_TREE_DIR = "context-tree";

const CATEGORY_DIRS: Record<MemoryCategory, string> = {
  decision: "decisions",
  pattern: "patterns",
  context: "context",
  learning: "learnings",
  todo: "active-work",
};

/**
 * Generate the full context tree as markdown files.
 * Called after every memory change (add, remove, mark_processed).
 */
export function generateContextTree(
  db: Database.Database,
  projectId: number,
  projectPath: string,
  config: PebbleConfig = DEFAULT_CONFIG
): void {
  const treeRoot = path.join(projectPath, PEBBLE_DIR, CONTEXT_TREE_DIR);

  // Ensure directories exist
  for (const dir of Object.values(CATEGORY_DIRS)) {
    const dirPath = path.join(treeRoot, dir);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
  }

  // Generate one file per category with all memories
  for (const [category, dirName] of Object.entries(CATEGORY_DIRS)) {
    const memories = getActiveMemories(db, projectId, category as MemoryCategory);
    const catConfig = config.categories[category as MemoryCategory];
    const filePath = path.join(treeRoot, dirName, "README.md");

    if (memories.length === 0) {
      // Remove file if no memories in this category
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
      }
      continue;
    }

    const content = formatTreeFile(category as MemoryCategory, memories, catConfig);
    fs.writeFileSync(filePath, content, "utf-8");
  }

  // Also generate a top-level summary file
  generateTreeIndex(db, projectId, treeRoot, config);
}

/**
 * Generate a single category file in the context tree.
 */
function formatTreeFile(
  category: MemoryCategory,
  memories: Memory[],
  catConfig: { emoji: string; label: string }
): string {
  const lines: string[] = [];

  lines.push(`# ${catConfig.emoji} ${catConfig.label}`);
  lines.push("");
  lines.push(`> Auto-generated by Pebble. ${memories.length} active memories.`);
  lines.push("");

  for (const mem of memories) {
    const date = mem.created_at.split("T")[0] || mem.created_at.split(" ")[0];
    const tags = mem.tags.length > 0 ? ` \`${mem.tags.join("` `")}\`` : "";
    const relevance = mem.relevance < 0.5 ? " _(fading)_" : "";

    lines.push(`## ${mem.content}`);
    lines.push("");
    lines.push(`- **Added:** ${date}${relevance}`);
    lines.push(`- **Source:** ${mem.source}`);
    if (tags) {
      lines.push(`- **Tags:**${tags}`);
    }
    lines.push(`- **ID:** ${mem.id}`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate the top-level index of the context tree.
 */
function generateTreeIndex(
  db: Database.Database,
  projectId: number,
  treeRoot: string,
  config: PebbleConfig
): void {
  const lines: string[] = [];

  lines.push("# 🪨 Pebble Context Tree");
  lines.push("");
  lines.push("> Your project's accumulated knowledge. Auto-generated by Pebble.");
  lines.push("> These files are human-readable, git-trackable, and can be read by any AI tool.");
  lines.push("");

  for (const [category, dirName] of Object.entries(CATEGORY_DIRS)) {
    const memories = getActiveMemories(db, projectId, category as MemoryCategory);
    const catConfig = config.categories[category as MemoryCategory];

    if (memories.length > 0) {
      lines.push(`## ${catConfig.emoji} [${catConfig.label}](./${dirName}/README.md) (${memories.length})`);
      lines.push("");
      // Show top 3 most relevant
      const top = memories.slice(0, 3);
      for (const mem of top) {
        lines.push(`- ${mem.content}`);
      }
      if (memories.length > 3) {
        lines.push(`- _...and ${memories.length - 3} more_`);
      }
      lines.push("");
    }
  }

  fs.writeFileSync(path.join(treeRoot, "README.md"), lines.join("\n"), "utf-8");
}
